import React, {useState} from 'react';
import Head from "next/head";
import Image from "next/image";
import logo from "../../public/assets/images/logo.png";

export type HeaderProps = {}

const Header: React.FC<HeaderProps> = () => {
    return (
        <>
            <Head>
                <title>Instasage: Read with friends</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="bg-white shadow py-2 md:py-5 sticky inset-x-0 top-0 z-20 px-5 flex items-center justify-between">
                <div className="flex items-center">
                    <Image src={logo} className="" height={40} width={40}/>
                    <h3 className="text-xl ml-2 font-semibold">Instasage</h3>
                </div>
                <div className="flex items-center justify-between">
                    <a href="" className="px-2 text-base">Books</a>
                    <a href="" className="px-2 text-base">Article</a>
                </div>
            </header>
        </>
    );
};

export default Header;
